### ISSUE TITLE
EMI Error

### ISSUE THREAD

**Issue by Erelaszun** [GlodBlock/ExtendedAE#271]
Bug, MC 1.21.1, Neoforge, Modpack created by me using MultiMC

This Error is preventing looking up ExtendedAE TE Recipes (Circut Slicer, Crystal Assembler, etc)
The game still plays, just no recipes:

[21:49:49] [Thread-473/ERROR] [EMI/]: [EMI] Exception loading plugin provided by extendedae
[21:49:49] [Thread-473/ERROR] [EMI/]: [EMI] java.lang.NoSuchMethodError: 'void sun.misc.Unsafe.ensureClassInitialized(java.lang.Class)'
	at TRANSFORMER
[21:49:49] [Thread-473/ERROR] [EMI/]: [EMI] glodium@1.21-2.1-neoforge
[21:49:49] [Thread-473/ERROR] [EMI/]: [EMI] com.glodblock.github.glodium.reflect.moon.Moon.getField(Moon.java:61)
	at TRANSFORMER
[21:49:49] [Thread-473/ERROR] [EMI/]: [EMI] glodium@1.21-2.1-neoforge
[21:49:49] [Thread-473/ERROR] [EMI/]: [EMI] com.glodblock.github.glodium.reflect.ReflectKit.readField(ReflectKit.java:54)
	at TRANSFORMER
[21:49:49] [Thread-473/ERROR] [EMI/]: [EMI] extendedae@1.21-2.1.1-neoforge
[21:49:49] [Thread-473/ERROR] [EMI/]: [EMI] com.glodblock.github.extendedae.util.Ae2ReflectClient.getInscribeRecipe(Ae2ReflectClient.java:70)
	at TRANSFORMER
[21:49:49] [Thread-473/ERROR] [EMI/]: [EMI] extendedae@1.21-2.1.1-neoforge
[21:49:49] [Thread-473/ERROR] [EMI/]: [EMI] com.glodblock.github.extendedae.xmod.emi.EMIPlugin.register(EMIPlugin.java:34)
	at TRANSFORMER
[21:49:49] [Thread-473/ERROR] [EMI/]: [EMI] emi@1.1.16+1.21.1+neoforge
[21:49:49] [Thread-473/ERROR] [EMI/]: [EMI] dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:185)
	at java.base
[21:49:49] [Thread-473/ERROR] [EMI/]: [EMI] java.lang.Thread.run(Thread.java:1575)

java.lang.NoSuchMethodError: 'void sun.misc.Unsafe.ensureClassInitialized(java.lang.Class)'
	at TRANSFORMER/glodium@1.21-2.1-neoforge/com.glodblock.github.glodium.reflect.moon.Moon.getField(Moon.java:61)
	at TRANSFORMER/glodium@1.21-2.1-neoforge/com.glodblock.github.glodium.reflect.ReflectKit.readField(ReflectKit.java:54)
	at TRANSFORMER/extendedae@1.21-2.1.1-neoforge/com.glodblock.github.extendedae.util.Ae2ReflectClient.getInscribeRecipe(Ae2ReflectClient.java:70)
	at TRANSFORMER/extendedae@1.21-2.1.1-neoforge/com.glodblock.github.extendedae.xmod.emi.EMIPlugin.register(EMIPlugin.java:34)
	at TRANSFORMER/emi@1.1.16+1.21.1+neoforge/dev.emi.emi.runtime.EmiReloadManager$ReloadWorker.run(EmiReloadManager.java:185)
	at java.base/java.lang.Thread.run(Thread.java:1575)

**Comment by GlodBlock** [comment]
could you provide the Java version?

**Comment by Erelaszun** [comment]
Oracle Java JDK 23

**Comment by Erelaszun** [comment]
Thank you! The latest Update released today corrected the issue! Recipes are working great now!
