### ISSUE TITLE
Crashed when open the paired wireless_connect pannel

### ISSUE THREAD

**Issue by 7934345** [GlodBlock/ExtendedAE#288]
neoforge 1.21.1

full log is here:  https://gist.github.com/7934345/b28d4964562e474281f78ebf5f68722d

**main crash log:**
> [1011月2024 20:50:31.824] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
> net.minecraft.ReportedException: Rendering screen
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1120) ~[client-1.21.1-20240808.144430-srg.jar%23452!/:?]
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.runTick(Minecraft.java:1195) ~[client-1.21.1-20240808.144430-srg.jar%23452!/:?]
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.Minecraft.run(Minecraft.java:807) ~[client-1.21.1-20240808.144430-srg.jar%23452!/:?]
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.main.Main.main(Main.java:230) ~[client-1.21.1-20240808.144430-srg.jar%23452!/:?]
> 	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source) ~[?:?]
> 	at java.base/java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
> 	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:136) ~[loader-4.0.31.jar%23112!/:4.0]
> 	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:124) ~[loader-4.0.31.jar%23112!/:4.0]
> 	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonClientLaunchHandler.runService(CommonClientLaunchHandler.java:32) ~[loader-4.0.31.jar%23112!/:4.0]
> 	at MC-BOOTSTRAP/fml_loader@4.0.31/net.neoforged.fml.loading.targets.CommonLaunchHandler.lambda$launchService$4(CommonLaunchHandler.java:118) ~[loader-4.0.31.jar%23112!/:4.0]
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-11.0.4.jar%23125!/:?]
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-11.0.4.jar%23125!/:?]
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-11.0.4.jar%23125!/:?]
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.run(Launcher.java:103) [modlauncher-11.0.4.jar%23125!/:?]
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.Launcher.main(Launcher.java:74) [modlauncher-11.0.4.jar%23125!/:?]
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-11.0.4.jar%23125!/:?]
> 	at MC-BOOTSTRAP/cpw.mods.modlauncher@11.0.4/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-11.0.4.jar%23125!/:?]
> 	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.run(BootstrapLauncher.java:210) [bootstraplauncher-2.0.2.jar:?]
> 	at cpw.mods.bootstraplauncher@2.0.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:69) [bootstraplauncher-2.0.2.jar:?]
> Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.core.RegistryAccess.lookup(net.minecraft.resources.ResourceKey)" because the return value of "net.minecraft.world.level.Level.registryAccess()" is null
> 	at TRANSFORMER/lithium@0.14.0-snapshot+mc1.21.1-build.88/net.caffeinemc.mods.lithium.common.world.LithiumData$Data.<init>(LithiumData.java:44) ~[lithium-neoforge-0.14.0-snapshot+mc1.21.1-build.88.jar%23607!/:?]
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.handler$bno000$lithium$initLithiumData(Level.java:3815) ~[client-1.21.1-20240808.144430-srg.jar%23452!/:?]
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.world.level.Level.<init>(Level.java:162) ~[client-1.21.1-20240808.144430-srg.jar%23452!/:?]
> 	at TRANSFORMER/ae2@19.0.23-beta/appeng.client.guidebook.scene.level.GuidebookLevel.<init>(GuidebookLevel.java:86) ~[appliedenergistics2-19.0.23-beta.jar%23474!/:?]
> 	at TRANSFORMER/ae2@19.0.23-beta/appeng.client.guidebook.scene.level.GuidebookLevel.<init>(GuidebookLevel.java:82) ~[appliedenergistics2-19.0.23-beta.jar%23474!/:?]
> 	at TRANSFORMER/extendedae@1.21-2.1.4-neoforge/com.glodblock.github.extendedae.client.gui.widget.WorldDisplay.locate(WorldDisplay.java:71) ~[ExtendedAE-1.21-2.1.4-neoforge.jar%23548!/:?]
> 	at TRANSFORMER/extendedae@1.21-2.1.4-neoforge/com.glodblock.github.extendedae.client.gui.GuiWirelessConnector.updateBeforeRender(GuiWirelessConnector.java:53) ~[ExtendedAE-1.21-2.1.4-neoforge.jar%23548!/:?]
> 	at TRANSFORMER/ae2@19.0.23-beta/appeng.client.gui.AEBaseScreen.render(AEBaseScreen.java:260) ~[appliedenergistics2-19.0.23-beta.jar%23474!/:?]
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.gui.screens.Screen.renderWithTooltip(Screen.java:112) ~[client-1.21.1-20240808.144430-srg.jar%23452!/:?]
> 	at TRANSFORMER/neoforge@21.1.74/net.neoforged.neoforge.client.ClientHooks.drawScreenInternal(ClientHooks.java:428) ~[neoforge-21.1.74-universal.jar%23453!/:?]
> 	at TRANSFORMER/neoforge@21.1.74/net.neoforged.neoforge.client.ClientHooks.drawScreen(ClientHooks.java:422) ~[neoforge-21.1.74-universal.jar%23453!/:?]
> 	at TRANSFORMER/minecraft@1.21.1/net.minecraft.client.renderer.GameRenderer.render(GameRenderer.java:1092) ~[client-1.21.1-20240808.144430-srg.jar%23452!/:?]
> 	... 18 more

**Comment by 7934345** [comment]
confirm conflic with The Twilight Forest
